# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252dd463f3cca11a9f5853d6fb37d6598f0823da93d1727d23a0794e589339f2d99a366c9b9ffd4e7eaf8a512f36566bc62d0bdcf84f19d3e45143eb6cf42dbb

test:
  secret_key_base: 4e15cdee54f92cacd557550e3af514cc3465aae3de0b22673dfcfc75402d1e8317865c2955042ab908d3a315fb8ce5cb312e1c9da60fc8ab5691b985e0222687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
